### ISSUE TITLE
Extension "sp_executesql to SQL" is not working

### ISSUE THREAD

**Issue by DanielAdeniji** [PejmanNik/sqlops-spexecutesql-to-sql#3] opened 2019-09-05 18:09 UTC
Azure Data Studio Version: 1.10.0
Extension :- sp_executesql to SQL
Versions :- 0.0.1 and 1.0.0

Steps to Reproduce

1. Add Extension - sp_executesql to SQL

2. Pasted SQL that contains sp_executesql

3. Sample SQL

sp_executesql
       N'select *
        from WideWorldImporters.Application.Countries
        where CountryName =  @_msparam_0'
 
     , N'@_msparam_0 varchar(4000)'
 
     , @_msparam_0=N'Brazil'

4. Selected SQL

5. Access Help/F1

6. Chose "sp_executesql to sql: convert" from menu

7. No conversion

Documented Here :-

Azure Data Studio – Extension – “sqlops-spexecutesql-to-sql”
https://learningintheopen.org/2019/08/24/azure-data-studio-extension-sqlops-spexecutesql-to-sql/

Thanks so very much,

Daniel Adeniji

**Comment by PejmanNik** [comment] 2019-09-06 19:53
It caused by extra white characters in your query. I'll fix it and release a new version until tomorrow.

**Comment by DanielAdeniji** [comment] 2019-09-06 20:59
Pejman :-
 
Thanks family.

Daniel

**Comment by PejmanNik** [comment] 2019-09-07 11:20
It is fixed in v1.0.1
Thank you

**Closed as completed by PejmanNik** 2019-09-07 11:20 UTC
Labels: bug
